### ISSUE TITLE
Question on Generating Video Samples

### ISSUE THREAD

**Issue by seokg** [rosinality/alias-free-gan-pytorch#11]
Hi!
First of all, thank you for sharing the implementation!

I was wondering about how you have generated the sample videos in the README file. Is there a code in the repo? In the [project page from NVIDIA](https://nvlabs.github.io/alias-free-gan/), they stated that the videos are generated by randomly walking around a central point in the latent space.

Thank you.

**Comment by rosinality** [comment]
Translation is achieved by affine transformation of input fourier features. Samples from NVIDIA also contains slight variations, and this is came from perturbation to latent vectors. (Random walking) I don't know how they did "randomly walk" latent spaces, but there are many known recipes for this kind of problem...
