### ISSUE TITLE
Questions on Filter parameters

### ISSUE THREAD

**Issue by MultiPath** [rosinality/alias-free-gan-pytorch#12]
Hi, sorry for asking a dumb question. I had a quite hard time (but still failed)  to understand the function of ```filter_parameters``` in https://github.com/rosinality/alias-free-gan-pytorch/blob/main/model.py#L47

It would be grateful if you can add some comments or explanations to this part. 
Moreover, especially if we want to change the input dimensions (instead of 16x16 for now), how should we modify this function?

Thanks

**Comment by rosinality** [comment]
It follows F.1 Flexible layer specifications from the paper. If you want to change input dimensions, you can either change cutoff & stopband or use alternative specifications. (For example Non-critical sampling from the 3.2.)

**Comment by MultiPath** [comment]
Thanks a lot! Will check in detail. 

The paper mentioned the fourier features part is to replace the original 4x4 matrices of StyleGAN2. However, in the current implementation, the first layer is 16x16 (and with margin 10, so it is 36x36). Is it also following F.1 setup?

Thanks again

**Comment by rosinality** [comment]
As initial sampling rate is 16, I thought authors might have used 16x16 input sizes. Or maybe they have used 8x upsamplings.

**Comment by MultiPath** [comment]
Got it! Thanks a lot for your answers.
