### ISSUE TITLE
Training Speed

### ISSUE THREAD

**Issue by nicolas-dufour** [rosinality/alias-free-gan-pytorch#14]
Hi!
The authors from the paper said that they needed to use a custom conda kernel to get acceptable performance (They say it's 20x faster than with pytorch primitives. I noticed u didn't use a custom cuda object. How is your performance compared to StyleGAN2?

Thanks!

**Comment by rosinality** [comment]
Config-T (3x3 conv) is quite similar to stylegan2, and Config-R (1x1 conv) is about 1.5x slower.
