### ISSUE TITLE
Required GPU Memory

### ISSUE THREAD

**Issue by obravo7** [rosinality/alias-free-gan-pytorch#15]
@rosinality thank you for always putting out such fantastic work. I have a questions about your training details: How much GPU memory is required, at minimum, to run this implementation of alias free gan? In the paper, the authors mention training on "n NVIDIA DGX-1 with 8 Tesla V100 GPUs", but no mention of how much GPU memory is required. Also, how long did it take you to train?

**Comment by rosinality** [comment]
I think config-t models used 14 GiB per gpu with 8 batch per gpu. And for 800k iterations with 4 P40, 32 batch without ada it used about 450 hours to train.
