### ISSUE TITLE
GPU Scalability Bug (GPU 0 has 4x the vram of all others)

### ISSUE THREAD

**Issue by Skylion007** [rosinality/alias-free-gan-pytorch#16]
![image](https://user-images.githubusercontent.com/2053727/127391148-5d7bb8bc-6755-41cb-bb29-f602bb73cae8.png)
I tried running this on multiple GPUs and noticed all the processes allocate memory on GPU number 1. This essentially limits me to a batch size of just 1 when each GPU can support closer to a batch size of 4 on their own.

**Comment by rosinality** [comment]
You can try to reduce training.n_sample in https://github.com/rosinality/alias-free-gan-pytorch/blob/main/config/config-t.jsonnet#L34.

**Comment by Skylion007** [comment]
Confirmed, the difference is entirely caused by the sampling code, I optimized it and submitted a PR.
