### ISSUE TITLE
Internal Representations

### ISSUE THREAD

**Issue by JonathanRayner** [rosinality/alias-free-gan-pytorch#18]
Thanks for the great contribution.

Slightly off-topic, but do you know how they generate the internal representations in Figure 6 in the original paper? ie. what convention do they use to visualise the channels in the feature maps as RGB?

**Comment by rosinality** [comment]
I don't have many clues, but I suspect they hand picked the channel of feature maps.

**Comment by JonathanRayner** [comment]
Okay cool, thanks!
