### ISSUE TITLE
Any tips or code for generating images and movies from the checkpoints?

### ISSUE THREAD

**Issue by MHRosenberg** [rosinality/alias-free-gan-pytorch#19]
Hi there, thanks so much for this implementation! I know this is probably trivial for more advanced users but could you provide some tips or code to accelerate my ability to generate images and movies. Something like what you [did](https://github.com/rosinality/stylegan2-pytorch/blob/master/generate.py) for StyleGAN2/ADA would be amazing.

**Comment by MHRosenberg** [comment]
I managed to (very crudely) hack the training.py to save images from the generator in the same format that is passed to the discriminator. They're low res though and also 1x4 (images not pixels) in a way that I didn't anticipate. Here's an [example](https://drive.google.com/file/d/13OV5M-MBHQPsWpCPzvOZUWNsJHvbKptg/view?usp=sharing). Ignore that it looks like trash; I have some samples/checkpoints that look somewhat more [reasonable](https://drive.google.com/file/d/10amdrls7e7gY2twYNuBKoTCIhMe2X2nn/view?usp=sharing), so the content issue is just a matter of the checkpoint / hyperparams. I'm hoping that the low resolution issue is because the size is 256 in config-t.jsonnet: 

training: {
        size: 256,
...

I'll probably try: 
1. trying to retrain with size params set to 512 or 1024, 
2. tinkering to see if I'm overlooking something trivial, and
3. just using another separate model to upscale the images.

Hints, suggestions, and code welcome. Thanks again for the implementation! I'm enjoying the learning process of reverse engineering your implementation.

**Comment by rosinality** [comment]
I have added generate.py to make sample videos at 9dfd1255823dab98608edb7d25e7f81cab05b6ce. You can may test it.

**Comment by MHRosenberg** [comment]
The code you provided appears to support the effect that pans around the latent space. Is there a way to get it to morph instead? I'm looking into hacking your generator.make_latent() function based on apply_factor.py. As before, hints / suggestions / code welcome.

**Comment by rosinality** [comment]
If you want to use closed form factorization, then you can extract eigenvectors almost same way with stylegan2.

```python
modulate = {k: v for k, v in ckpt['g_ema'].items() if 'modulation' in k and 'to_rgb' not in k and 'weight' in k}
weight_mat = []
for k, v in modulate.items():
    weight_mat.append(v)
    
W = torch.cat(weight_mat, 0)
eigvec = torch.svd(W).V.to('cpu')
```

**Comment by MHRosenberg** [comment]
Thanks! Is [this](https://openaccess.thecvf.com/content/CVPR2021/papers/Shen_Closed-Form_Factorization_of_Latent_Semantics_in_GANs_CVPR_2021_paper.pdf) the method you suggested? Any tips for how to add the scaled eigenvector (alpha n) to the existing latent vector z in your code? However, the method appears to slightly vary a single reasonable image rather than morph between multiple reasonable images. In other words, so far my latent space seems to only contain a single image that resembles my training dataset. I've tried hacking your transform to make it linear rather than a circle. This works but I only encounter one reasonable 'fake' in the latent walk rather than multiple; away from the center the images just look like filtered noise. With [this](https://github.com/dvschultz/stylegan2-ada-pytorch/blob/main/generate.py) styleGAN2 generator, it appears possible to traverse the space and get multiple reasonable "fakes" in addition to the crazy artifactual images. Does the alias-free GAN generate a latent space in which this is possible? I realize these questions are probably very naive. I'll keep reading, reverse engineering, and playing with your generator and transform code. Further support is welcome, but I appreciate your time so far!

**Comment by rosinality** [comment]
As you mentioned apply_factor.py, I thought you want to apply closed form factorization. Anyway, with enough weight to eigenvectors you can get different images from original images.

Actually, there are many ways to perturb latent codes meaningfully. You can may apply slerp to 2 distinct latent codes, and so on. And affine transforms in the generate.py just moves coordinates, so it just affine transforms the image, and it will not produce semantically distinct images.
