### ISSUE TITLE
pretrained model 

### ISSUE THREAD

**Issue by betterze** [rosinality/alias-free-gan-pytorch#3]
Dear Rosinality,

Thank you for you great implementation. 

Would you mind providing the pretrained models? Maybe for unaligned FFHQ?

Thank you for your help.

Best Wishes,

Alex

**Comment by rosinality** [comment]
I'm currently testing on FFHQ, but you can may testing intermediate checkpoints. https://www.dropbox.com/s/97gpiyh0rjbonem/280000.pt?dl=0

**Comment by betterze** [comment]
Thx a lot.

**Comment by duskvirkus** [comment]
@rosinality Trying to get this working on my version but I'm getting errors with tensor sizes. Would be helpful to know what size this model is. I'm assuming 1024 but please let me know if that's wrong?

Also wanted to check and see if it's alright to host this checkpoint on my google drive for others to use?

Don't know if you have a checkpoint that's farther along you're willing to share?

**Comment by rosinality** [comment]
@duskvirkus This is 256px model. You can use 800k checkpoints https://www.dropbox.com/s/ydqw5pb6cu7trxt/config-t_800k.pt?dl=0 freely.
