### ISSUE TITLE
CUDA error: illegal memory access was encountered

### ISSUE THREAD

**Issue by matigekunstintelligentie** [rosinality/alias-free-gan-pytorch#6]
I'm getting the following error in stylegan2/op/fused_act.py at line 66:

> RuntimeError: CUDA error: an illegal memory access was encountered

Did not use the docker file and I'm running on torch 1.8.1 and I'm running on a 3090

**Comment by matigekunstintelligentie** [comment]
Pytorch 1.7.1 from the docker file does not have the sinc operator used in the lowpass operator

**Comment by rosinality** [comment]
Sorry, I thought I using 1.7.1. It would be better to update the version in the dockerfile.
Regarding to CUDA error, I don't have much clue on it. I will look into it.

**Comment by matigekunstintelligentie** [comment]
Got it to work by reducing the resolution from 1024 to 256. Pytorch 1.7.1 gives multiple bugs, but 1.8 works!
