### ISSUE TITLE
How much GPU memory do I need to train?

### ISSUE THREAD

**Issue by andorxornot** [rosinality/alias-free-gan-pytorch#7]
Hi! I wanted to try this GAN, but I don't have enough memory to run it. I have a 1080ti 11gb and used training.batch=1
Is there any way to optimize the network so that it fit?

**Comment by rosinality** [comment]
You can may try to reduce training.n_sample.

**Comment by andorxornot** [comment]
yeah, `training.n_sample=16` works!

**Comment by obravo7** [comment]
@andorxornot I am in a similar situation. I haven't trained yet, but I am curious what resolution you trained on? Thanks!
